site_name: EBGA Framework
site_description: Evolutionary-Based Gradient-Free Architecture for Machine Learning
site_author: Giuseppe Gallitto

use_directory_urls: false

theme:
  name: mkdocs

nav:
  - Home: index.md
  - API Reference: api.md

markdown_extensions:
  - codehilite
  - admonition
  - toc:
      permalink: true

repo_url: https://codeberg.org/Nevdyf/EBGA
repo_name: EBGA
